# Generated by Django 3.1.6 on 2021-04-06 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='first_name', max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(db_column='Last_name', max_length=100, verbose_name='Last Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('contactNo', models.CharField(max_length=10)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_column='project_name', max_length=200, verbose_name='project name')),
                ('description', models.TextField(blank=True, null=True)),
                ('projectLink', models.URLField(blank=True, db_column='Project_Link', null=True, verbose_name='Project link')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('JoinedYear', models.DateField(db_column='joined_year', max_length=4, verbose_name='company joined year')),
                ('leftYear', models.DateField(blank=True, db_column='Left_year', max_length=4, null=True, verbose_name='company left year')),
                ('JobTitle', models.CharField(db_column='Job_title', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200, verbose_name='Course name(ex Bsc csit)')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='University')),
                ('joinedYear', models.CharField(db_column='joined_year', max_length=4)),
                ('passYear', models.DateField(blank=True, db_column='passed_year', max_length=4, null=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(db_column='skill_name', max_length=30)),
                ('level', models.IntegerField(verbose_name='level of Knowledge out of 100')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'skill',
                'unique_together': {('skillName', 'employee')},
            },
        ),
    ]
